output "storage_account_name" {
  value = var.nfs_share_enabled ? null : azurerm_storage_account.storage_account.name
  description = "Storage account name"
}
/*
output "primary_access_key" {
  # Note nonsensitive is not recommended for production use
  # This is used here only to simplify the deployment of this sample
  value = var.nfs_share_enabled ? null : nonsensitive(azurerm_storage_account.storage_account.primary_access_key) 
}*/

output "azure_files_share" {
  value = azurerm_storage_share.azurefileshare.name
  description = "azure files share name"
}

output "azure_files_protocol" {
  value = var.nfs_share_enabled ? "nfs" : "smb"
  description = "azure files protocol"
}

output "helm_sample_command" {  
  value = "helm install --generate-name fio-perf-job-1.0.0.tgz -f fio-perf-job/values.yaml --set-file=fioconfig=./fio-perf-job/config/fiorandreadiops.ini --set storageclass.parameters.storageAccountName=${azurerm_storage_account.storage_account.name} --set storageclass.parameters.shareName=${azurerm_storage_share.azurefileshare.name} --set storageclass.parameters.protocol=${var.nfs_share_enabled ? "nfs" : "smb"}"
  description = "Example helm command to deploy fio chart. The package name should reflect the version of the chart generated by the helm package command. e.g. helm package fio-perf-job --version=1.0.0"
}
/*
output "create_secret" {
    value = var.nfs_share_enabled ? null : "kubectl create secret generic azure-secret --from-literal=azurestorageaccountname=${azurerm_storage_account.storage_account.name} --from-literal=azurestorageaccountkey=${nonsensitive(azurerm_storage_account.storage_account.primary_access_key)}"
}*/